application: gullygallery
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /static
  static_dir: static

- url: /.*
  script: main.py 
